install:
    crash_reporting:
        enabled: true
        type: "crashpad"
    game-settings:
        accountId: 200982764
        modified: false
        timestamp: 0
    gameflow-patcher-lock: null
    gameflow-process-info: null
    gameflow-spectate-reconnect-info: null
    globals:
        locale: "ko_KR"
        region: "BR"
        userLocale: "ko_KR"
    lcu-settings:
        accountId: 200982764
        modified: false
        timestamp: 0
    patcher:
        client_migrated: true
        client_patcher_available: true
        game_migrated: true
        game_patcher_available: true
        locales:
        - "ko_KR"
        - "pt_BR"
        toggles:
            new_client_patcher: 0
            new_game_patcher: 0
    perks-settings:
        accountId: 200982764
        modified: false
        timestamp: 0
    riotclient-upgrade:
        seq-success-count: 118
        success-count: 118
    rso-auth:
        install-identifier: "b6f33fc4b3b3254aa5c86dd8250740d7"
    tft-settings:
        accountId: 200982764
        modified: false
        timestamp: 0
